# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-11 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('coord_lon', models.FloatField()),
                ('coord_lat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Clouds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cloud', models.CharField(max_length=100)),
                ('icon', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('wind', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('sunrise', models.DateTimeField()),
                ('sunset', models.DateTimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.City')),
                ('cloudiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.Clouds')),
            ],
            options={
                'ordering': ['city', 'date'],
            },
        ),
    ]
