# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='request',
            name='sunrise',
        ),
        migrations.RemoveField(
            model_name='request',
            name='sunset',
        ),
        migrations.RemoveField(
            model_name='request',
            name='wind',
        ),
        migrations.AddField(
            model_name='request',
            name='wind_degree',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='wind_speed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clouds',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='pressure',
            field=models.IntegerField(),
        ),
    ]
