# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20170623_2118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clouds',
            new_name='Cloud',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='cloud',
            options={'verbose_name': 'Cloud', 'verbose_name_plural': 'Clouds'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['city', 'date'], 'verbose_name': 'Request', 'verbose_name_plural': 'Requests'},
        ),
    ]
