# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20170623_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(),
        ),
    ]
