# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20170623_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud',
            name='cloud_id',
            field=models.CharField(default='0d', max_length=3),
            preserve_default=False,
        ),
    ]
